// Usage: npm run build:border [-- <fill distance km> <simplify tolerance degrees>]
// Builds docs/germany.js, the outline of Germany drawn on the map:
// - mainland (incl. peninsulas) plus Rügen; the other islands are left out
// - along the north coast narrow waterways (Bodden, Strelasund, estuaries, fjords) are filled in
// - the whole outline is simplified and rounded off so it runs smoothly instead of jagged
const topo = require('world-atlas/countries-10m.json');
const { feature } = require('topojson-client');
const turf = require('@turf/turf');

const D_KM = Number(process.argv[2] || 8);           // inlets narrower than ~2*D are filled
const TOLERANCE = Number(process.argv[3] || 0.012);  // simplification in degrees (~1 km)
const NORTH_LAT = 53.25;                             // waterways are only filled north of this latitude
const KEEP_ISLANDS = [[13.4, 54.45]];                // Rügen (a point on the island)

const area = (ring) => {
  let a = 0;
  for (let i = 0; i < ring.length - 1; i++) a += ring[i][0] * ring[i + 1][1] - ring[i + 1][0] * ring[i][1];
  return Math.abs(a / 2);
};
const largestRing = (geometry) => {
  const polys = geometry.type === 'Polygon' ? [geometry.coordinates] : geometry.coordinates;
  return polys.reduce((b, p) => (area(p[0]) > area(b[0]) ? p : b))[0];
};

const de = feature(topo, topo.objects.countries).features.find((f) => f.id === '276');
const parts = de.geometry.coordinates.map((p) => turf.polygon([p[0]]));
const mainland = turf.polygon([largestRing(de.geometry)]);
const islands = parts.filter((p) => KEEP_ISLANDS.some((pt) => turf.booleanPointInPolygon(turf.point(pt), p)));
const land = turf.union(turf.featureCollection([mainland, ...islands]));

// Fill narrow waterways in the north (closing = grow, then shrink by the same distance).
const closed = turf.buffer(turf.buffer(land, D_KM, { units: 'kilometers', steps: 16 }), -D_KM, { units: 'kilometers', steps: 16 });
const fill = turf.intersect(turf.featureCollection([closed, turf.bboxPolygon([0, NORTH_LAT, 20, 60])]));
const merged = turf.union(turf.featureCollection([land, fill]));

// One outline without holes, simplified and rounded off (Chaikin smoothing).
let shape = turf.polygon([largestRing(merged.geometry)]);
shape = turf.simplify(shape, { tolerance: TOLERANCE, highQuality: true });
shape = turf.polygonSmooth(shape, { iterations: 2 }).features[0];

const round = (c) => [Math.round(c[0] * 1e4) / 1e4, Math.round(c[1] * 1e4) / 1e4];
const coords = [shape.geometry.coordinates[0].map(round)];
const out = `/* Border of Germany (GeoJSON geometry), drawn as a smooth outline: mainland and Rügen (other
 * islands left out), narrow waterways along the north coast filled in, simplified and rounded off.
 * Source: Natural Earth 1:10m admin-0 countries via world-atlas (public domain).
 * Generated by tools/build-border.js. */
window.GERMANY_BORDER = ${JSON.stringify({ type: 'Polygon', coordinates: coords })};
`;
require('fs').writeFileSync(process.argv[4] || require('path').join(__dirname, '..', 'docs', 'germany.js'), out);
console.log(`fill ${D_KM} km, tolerance ${TOLERANCE}°, islands kept ${islands.length}; points ${coords[0].length}, ${out.length} bytes`);
